version: "3.4"
services:

  idp:
    build:
      context: .docker/idp
    volumes:
      - "./idp:/var/www/html:${VOLUME_CONSISTENCY:-consistent}"
      - "./idp.ini:/usr/local/etc/php/conf.d/my.ini:ro"
    environment:
      - HOST_UID
      - HOST_GID
      - "XDEBUG_PORT=${IDP_XDEBUG_PORT:-9000}"
      - "XDEBUG_HOST=${IDP_XDEBUG_HOST:-}"
    ports:
      - "${IDP_HTTP_PORT:-80}:80"
