version: "3.4"
services:

  idp:
    build:
      context: .docker/idp
    volumes:
      - "./idp:/var/www/html:${VOLUME_CONSISTENCY:-consistent}"
      - "./idp.ini:/usr/local/etc/php/conf.d/my.ini:ro"
    environment:
      - HOST_UID
      - HOST_GID
      - "XDEBUG_PORT=${IDP_XDEBUG_PORT:-9000}"
      - "XDEBUG_HOST=${IDP_XDEBUG_HOST:-}"
    ports:
      - "${IDP_HTTP_PORT:-8000}:80"

  sp1:
    build:
      context: .docker/sp
    volumes:
      - "./sp:/var/www/html:${VOLUME_CONSISTENCY:-consistent}"
      - "./sp.ini:/usr/local/etc/php/conf.d/my.ini:ro"
    environment:
      - HOST_UID
      - HOST_GID
      - "XDEBUG_PORT=${SP_XDEBUG_PORT:-9000}"
      - "XDEBUG_HOST=${SP_XDEBUG_HOST:-}"
      - "APP_URL=http://localhost:${SP1_HTTP_PORT:-8080}/"
      - "SP_ID=${SP1_ID:-sp1}"
    ports:
      - "${SP1_HTTP_PORT:-8080}:80"

  sp2:
    build:
      context: .docker/sp
    volumes:
      - "./sp:/var/www/html:${VOLUME_CONSISTENCY:-consistent}"
      - "./sp.ini:/usr/local/etc/php/conf.d/my.ini:ro"
    environment:
      - HOST_UID
      - HOST_GID
      - "XDEBUG_PORT=${SP_XDEBUG_PORT:-9000}"
      - "XDEBUG_HOST=${SP_XDEBUG_HOST:-}"
      - "APP_URL=http://localhost:${SP2_HTTP_PORT:-8888}/"
      - "SP_ID=${SP2_ID:-sp2}"
    ports:
      - "${SP2_HTTP_PORT:-8888}:80"
